apiVersion: v1
kind: Service
metadata:
  namespace: kubecms
  name: kubecms-registry
  labels:
    app: kubecms
    service: kubecms-registry
spec:
  selector:
    app: kubecms
    service: kubecms-registry
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 80