apiVersion: v1
kind: Service
metadata:
  namespace: kubecms
  name: kubecms-queue
  labels:
    app: kubecms
    service: kubecms-queue
spec:
  selector:
    app: kubecms
    service: kubecms-queue
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 80