apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kubecms
  name: kubecms-backoffice-pvc
  labels:
    app: kubecms
    service: kubecms-backoffice
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi