apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: kubecms
  name: kubecms-backoffice-pv
  labels:
    app: kubecms
    service: kubecms-backoffice
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/kubecms/backoffice/