  
name: backoffice
on:
  create:
    ref_type: tag
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      DOCKER_REPO: kubecms
      DOCKER_PLATFORMS: >
        linux/amd64
        linux/arm/v7
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set Up Image Tag
      run: |
        set -vx
        echo "::set-env name=TAG::${GITHUB_REF/refs\/tags\//}"
        echo "::set-env name=DOCKER_BASE::${DOCKER_REPO}/${DOCKER_REPO}"
    - name: Install Docker buildx
      run: |
        set -vx
        docker_apt_repo='https://download.docker.com/linux/ubuntu'
        curl -fsSL "${docker_apt_repo}/gpg" | sudo apt-key add -
        os="$(lsb_release -cs)"
        sudo add-apt-repository "deb [arch=amd64] $docker_apt_repo $os stable"
        sudo apt-get update
        sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
        config='/etc/docker/daemon.json'
        if [[ -e "$config" ]]; then
          sudo sed -i -e 's/{/{ "experimental": true, /' "$config"
        else
          echo '{ "experimental": true }' | sudo tee "$config"
        fi
        sudo systemctl restart docker
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --name mybuilder
        docker buildx use mybuilder
        docker buildx inspect --bootstrap
    - name: Build multi-architecture Docker images with buildx
      run: |
        set -vx
        echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USER" --password-stdin
        docker buildx build --platform ${DOCKER_PLATFORMS// /,} --push --file ./src/backoffice/dockerfile --tag "$DOCKER_BASE:$TAG" ./src/backoffice/