name: backoffice
on:
  create:
    ref_type: tag
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - run: docker buildx build --push --tag kubecms/kubecms-backoffice:latest,${{ steps.get_version.outputs.VERSION }} --platform linux/amd64,linux/arm ./src/backoffice ./src/backoffice/dockerfile