name: data
on:
  create:
    ref_type: tag
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: kubecms/kubecms-data
        tag_with_ref: true
        tags: latest
        dockerfile: src/data/dockerfile