name: registry

on:
  create:
    ref_type: tag

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Build & Push Image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: kubecms/kubecms-registry
        tag_with_sha: true
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
